a = int(input('DIGITE O VALOR A:\n'))
b = int(input('DIGITE O VALOR B:\n'))
c = int(input('DIGITE O VALOR C:\n'))
d = int(input('DIGITE O VALOR D:\n'))
dif = (a * b) - (c * d)
print(f'DIFERENCA = {dif}')
